version: "3.8"

services:
  traefik:
    image: traefik:v2.10.7
    restart: unless-stopped
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_ACME_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-letsencrypt:/letsencrypt
    networks:
      - web

  app:
    image: prode-404:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
      HOSTNAME: 0.0.0.0
      PORT: 3000
    labels:
      - traefik.enable=true
      - traefik.docker.network=prode-web
      - traefik.http.routers.prode.rule=Host(`${APP_DOMAIN}`)
      - traefik.http.routers.prode.entrypoints=websecure
      - traefik.http.routers.prode.tls=true
      - traefik.http.routers.prode.tls.certresolver=letsencrypt
      - traefik.http.services.prode.loadbalancer.server.port=3000
    networks:
      - web
      - app

  migrate:
    image: prode-404-tools:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: tools
    env_file:
      - .env
    command: npm run db:migrate
    networks:
      - app

  sync-once:
    image: prode-404-tools:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: tools
    env_file:
      - .env
    command: npm run sync:football-data
    networks:
      - app

volumes:
  traefik-letsencrypt:

networks:
  web:
    name: prode-web
  app:
    name: prode-app
